### ISSUE TITLE
add login window support to capture password

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#12]
Add login window support to capture password and use instead of prompting.

**Comment by dechkovanen** [comment]
JIT user creation while at it?
- Shortname based on partial UPN
- Admin privileges either always (some boolean like CreateAdminUsersByDefault, maybe default to true) or for specified AAD groups (CreateAdminByGroupMembers, array of strings which would be AAD object identifiers for groups).
- CreateStandardByGroupMembers so that even if CreateAdminUsersByDefault is set to true, members of these groups are created as standard.
- Verify user groups upon each login and add/remove admin privileges based on settings.
- Detect macOS updates and remediate login window settings accordingly (updates are known to break login window plugins).

**Comment by twocanoes** [comment]
the base issue has been implemented. please file individual issues for ones that are not implemented and you still want.
