### ISSUE TITLE
AD password change

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#200]
Detect when AD password requires a change and provide a native UI to change.

**Comment by twocanoes** [comment]
need a customer request for this feature since not sure how needed it is. slating for future

**Comment by srobin2uw** [comment]
Hi there! We would appreciate this feature for our shared computers, so that our users don't have to go to another computer to reset their password

**Comment by dstranathan** [comment]
I believe I have mentioned this before out of curiosity when I was test 100% AD and used to only NoMAD in the past.

It would be a cool option to be able commit a password change via XCreds to a DC (similar to NoMAD), rather than needing extra hops to redirect to a web portal.

How would this work? 

If on the domain and a DC can be reached you pop up a native app pw change box that talks to AD directly (like NoMAD).
If no domain is detected, then pop up the current password change web portal?

**Comment by dstranathan** [comment]
Im currently using a menu item pointed to Ticket Viewer. Mainly for IT QA and support purposes. Im not opposed to this but doe to the nature of Kerberos and how abstract it is as an idea to normal end users, my CIO has been opposed to this has a long-term solution. It hasn't been brought up again, but it might in future conversations.
