### ISSUE TITLE
Issue with HomeMountEnabled

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#236]
v5.0 build 7066

There may be an issue with AD shares `HomeMountEnabled`.  The home share did not appear to get mounted when setting this true and launching the menubar app.  Log is attached.  

[xcreds.log](https://github.com/user-attachments/files/15905732/xcreds.log)

**Comment by dstranathan** [comment]
On my test Mac running XCReds 5.0 7087, I see the opposite:

I have the key `HomeMountEnabled` set to `false` and it is still auto-mounting - maybe these booleans are flipped?

**Comment by twocanoes** [comment]
HomeMountEnabled is to show in menu not automatically mount. What is expected behavior?

**Comment by dstranathan** [comment]
I have the key set to false but I still see the 'Network Home'  in the menu bar drop-down. 

I dont want it to show at my org because we dont use AD homes in a traditional sense. To compare, NoMAD does not exhibit this behavior.  I may need to screen share this with you as it may be hard to articulate in this thread. Our SMB file server uses down-level-mapping and a $username  variable to map SMB homes (I can demonstrate this to you as needed on both NoMAD and XCreds 5).


Screenshot 2024-07-22 at 11.49.37

**Comment by twocanoes** [comment]
I think i found the issue.  please test and close if works as expected.

**Comment by dstranathan** [comment]
Tested build 7130 on multiple Macs:  Setting _HomeMountEnabled_ to false is working as expected for me now. "Network Home" no longer appears in the Xcreds Shares drop-down menu

Thank you!
