### ISSUE TITLE
Please provide a Jamf JSON MDM Profile Schema

### ISSUE THREAD

**Issue by dgreening** [twocanoes/xcreds#24]
It would be lovely if you could provide a JSON Schema for Jamf MDM profile creation so we don't have to mess about with Profile Creator or other methods, and can simply plug the necessary values in.

**Comment by everetteallen** [comment]
Until something formal can be done
https://files.slack.com/files-pri/T04QVKUQG-F03MVMKUKPG/download/com.twocanoes.xcreds.json.zip?origin_team=T04QVKUQG

**Comment by apizz** [comment]
This will be available via the ProfileManifestsMirror repo once the related PR is merged, which will be soon!

**Comment by kenchan0130** [comment]
This issue may have already been resolved.

https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.twocanoes.xcreds.json

**Comment by beckf** [comment]
+1 for Jamf-Custom-Profile-Schemas.  Used this today.

**Comment by kenchan0130** [comment]
I honestly find https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.twocanoes.xcreds.json difficult to use.
This is because `anyOf` etc. in JSON Schema is not used.

I ended up writing my own JSON Schema.
https://kenchan0130.github.io/assets/posts/post/2022-09-15-1/com.twocanoes.xcreds.json

**Comment by apizz** [comment]
@kenchan0130 you literally just copy and paste the contents of the file in Jamf...

**Comment by kenchan0130** [comment]
I am not saying that the method is difficult. I meant to say that the contents of [that schema](https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.twocanoes.xcreds.json) are not user-friendly.
