### ISSUE TITLE
Pin item based on available space

### ISSUE THREAD

**Issue by davelebbing** [twocanoes/xcreds#255]
From @uurazzle mentioned in earlier issue #154

How about providing options to pin items based on available space or font size?

Or options to implement custom text based on the script? Like checking > 30 days, OS updates available, etc. or many other options based on the needs of the organization using Xcreds. Also, would this support emojis to give other options outside font color to highlight important items, etc?

Like for example
🛜 SSID: [SSID]
🏷️ Name: MAC1234

**Comment by twocanoes** [comment]
implemented. see new key systemInfoAdditionsArray

**Comment by uurazzle** [comment]
Hi @davelebbing ,

Just to clarify, do we still need to manually click to display the system information? It would be really helpful in our environment to have the option to always show system information without requiring a manual click. I understand that some environments might not want this for privacy or security reasons, but others would benefit from always displaying it. Perhaps a parameter could be added to enable or disable this feature, depending on preference.

**Comment by davelebbing** [comment]
Hi @uurazzle.  System info in v5.1 now defaults to showing the popup every time.  This can be turned off if desired using the `shouldActivateSystemInfoButton` pref.

**Comment by uurazzle** [comment]
Hi @davelebbing,

Is the system info currently only controlled or displayed by a popup toggle? What I’m requesting is the ability to display the information directly on the Xcreds login window without using a popup, so the text is always visible.

**Comment by davelebbing** [comment]
@uurazzle the info is shown in a popup but it defaults to being shown without having to click on it.

**Comment by uurazzle** [comment]
HI @davelebbing, I don't want to click to show a popup, but want certain info to always show on the xcreds window without clicking or showing the pop-up. Does that make sense?

**Comment by uurazzle** [comment]
Ok, we will test and report back. Bronson Bohnet on our team is working on the Xcreds project and will test.

Thanks:

[Block U Logo]
Richard Glaser  (he, him, his)
Assistant Head, Client Platform Services
Marriott Library ITDLS
The University of Utah
On Nov 1, 2024 at 12:04 PM -0600, Twocanoes Software, Inc ***@***.***>, wrote:

I made it so that you can force the popover to always show and not require any click. See the video here:

https://twocanoes.com/knowledge-base/whats-new-in-xcreds-5-1/

around the 1 minute. Is this sufficient for what you are asking?

tim

**Comment by uurazzle** [comment]
Hi @twocanoes:

Yes, it is working properly for us and looks good, thx.

![image](https://github.com/user-attachments/assets/bd52ca2e-929f-41ff-8be2-1c6dd9b7d0f1)
